CustomerRelationManagement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("crm.urls"))
]

crm/urls.py
from django.urls import path
from crm import views

urlpatterns=[
    path("departments/add",views.Departments.as_view(),name="department"),
    path("employees/add",views.UserRegistration.as_view(),name="signup"),
    path("",views.SignIn.as_view(),name="signin"),
    path("accounts/signout",views.signout,name="signout"),
    path("employees/all",views.Employees.as_view(),name="employees"),
    path("employee/<int:id>",views.EmployeeDetail.as_view(),name="empdetail"),
    path("employee/change/<int:id>",views.EmployeeChange.as_view(),name="employeechange")
]

crm/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager

# Create your models here.

class MyUserManager(BaseUserManager):
    # ['designation','first_name','last_name','phone','address1','address2','city','state','pin',
    #                        'department']
    def create_user(self, email, designation,first_name,last_name,phone,address1,address2,city,state,pin, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            designation=designation,
            first_name=first_name,
            last_name=last_name,
            phone=phone,
            address1=address1,
            address2=address2,
            city=city,
            state=state,
            pin=pin
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,

        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class Department(models.Model):
    dept_name=models.CharField(max_length=120,unique=True)

    def __str__(self):
        return self.dept_name

class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    designation=models.CharField(max_length=50)
    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    address1=models.CharField(max_length=120)
    address2=models.CharField(max_length=120)
    city=models.CharField(max_length=120)
    options=(("kerala","kerala"),
             ("ThamilNadu", "ThamilNadu"),
             ("Mumbai","Mumbai"),
             ("Delhi","Delhi"),
             ("pune","pune")

             )
    state=models.CharField(max_length=120,choices=options,default="Mumabi")
    pin=models.CharField(max_length=50)
    department=models.ForeignKey(Department,on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)


    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['designation','first_name','last_name','phone','address1','address2','city','state','pin',
                       'department']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

crm/forms.py
from django.forms import ModelForm
from crm.models import Department,MyUser
from django import forms
from django.core.exceptions import ValidationError

class DepartmentForm(ModelForm):
    class Meta:
        model=Department
        fields=["dept_name"]


class MyUserCreationForm(ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    class Meta:
        model=MyUser
        exclude=("password","is_active","is_admin","last_login")

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password2"])
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):
    email=forms.CharField(widget=forms.EmailInput(attrs={"class":"form-control"}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control"}))

crm/views.py
from django.shortcuts import render,redirect
from .forms import DepartmentForm,MyUserCreationForm,LoginForm
from django.urls import reverse_lazy
# Create your views here.
from crm.models import *
from django.views.generic import CreateView,TemplateView,ListView,DetailView,UpdateView

from django.contrib.auth import authenticate,login,logout



class Departments(CreateView):
    template_name = "add_dept.html"
    form_class = DepartmentForm
    model = Department
    success_url = reverse_lazy("department")


    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context["departments"]=self.model.objects.all()
        return context

class UserRegistration(CreateView):
    model=MyUser
    form_class = MyUserCreationForm
    template_name = "register.html"
    success_url = reverse_lazy("department")

class SignIn(TemplateView):
    template_name = "signin.html"
    form_class=LoginForm
    model=MyUser
    context={}

    def get(self, request, *args, **kwargs):
        form=self.form_class()
        self.context["form"]=form
        return render(request,"signin.html",self.context)
    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            email=form.cleaned_data["email"]
            password=form.cleaned_data["password"]
            user=authenticate(request,username=email,password=password)
            if user:
                login(request,user)
                return render(request,"home.html")
            else:
                self.context["form"]=form
                return render(request, "signin.html", self.context)
        else:
            self.context["form"] = form
            return render(request, "signin.html", self.context)

def signout(requset):
    logout(requset)
    return redirect("signin")


class Employees(ListView):
    template_name = "employees.html"
    model=MyUser
    context_object_name = "employees"

class EmployeeDetail(DetailView):
    template_name = "emp_detail.html"
    model=MyUser
    context_object_name = "employee"
    pk_url_kwarg = "id"

class EmployeeChange(UpdateView):
    template_name = "employee_change.html"
    model = MyUser
    form_class = MyUserCreationForm
    success_url = reverse_lazy("department")
    pk_url_kwarg = "id"

crm/templates/add_dept.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #5000ca">
        <div class="container">
          <a class="navbar-brand text-white" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{%url 'signup' %}">AddNewEmployee</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white" href="{%url 'employees' %}">ListAllEmployees</a>
              </li>


            </ul>
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="" class="nav-link text-white">contactUs</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'signout' %}" class="nav-link text-white">LogOut</a>
                </li>
            </ul>

          </div>
        </div>
      </nav>
<div class="container">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
      <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="create">
      </form>
    </div>
    <div class="col-2"></div>
  </div>

  <div class="container">
    {{departments}}
  </div>
</div>



<foooter style="position:fixed;bottom:0;">

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#5000ca" fill-opacity="1" d="M0,256L34.3,245.3C68.6,235,137,213,206,186.7C274.3,160,343,128,411,138.7C480,149,549,203,617,213.3C685.7,224,754,192,823,186.7C891.4,181,960,203,1029,218.7C1097.1,235,1166,245,1234,245.3C1302.9,245,1371,235,1406,229.3L1440,224L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z"></path></svg>

</foooter>
</body>
</html>

crm/templates/emp_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #5000ca">
        <div class="container">
          <a class="navbar-brand text-white" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{%url 'signup' %}">AddNewEmployee</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white" href="{%url 'employees' %}">ListAllEmployees</a>
              </li>


            </ul>
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="" class="nav-link text-white">contactUs</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'signout' %}" class="nav-link text-white">LogOut</a>
                </li>
            </ul>

          </div>
        </div>
      </nav>
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">

             <table class="table">

                <tr>
                    <td>Employeename</td>
                    <td>phone</td>
                    <td>email</td>
                    <td>Depertmeyt</td>
                    <td colspan="3">Action</td>
                </tr>

                <td>{{employee.first_name}}</td>
                <td>{{employee.email}}</td>
                <td>{{employee.phone}}</td>
                <td>{{employee.department}}</td>




            </table>


        </div>
        <div class="col-4"></div>
    </div>
</div>
<foooter style="position:fixed;bottom:0;">

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#5000ca" fill-opacity="1" d="M0,256L34.3,245.3C68.6,235,137,213,206,186.7C274.3,160,343,128,411,138.7C480,149,549,203,617,213.3C685.7,224,754,192,823,186.7C891.4,181,960,203,1029,218.7C1097.1,235,1166,245,1234,245.3C1302.9,245,1371,235,1406,229.3L1440,224L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z"></path></svg>

</foooter>

</body>
</html>

crm/templates/employee_change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #5000ca">
        <div class="container">
          <a class="navbar-brand text-white" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{%url 'signup' %}">AddNewEmployee</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white" href="{%url 'employees' %}">ListAllEmployees</a>
              </li>


            </ul>
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="" class="nav-link text-white">contactUs</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'signout' %}" class="nav-link text-white">LogOut</a>
                </li>
            </ul>

          </div>
        </div>
      </nav>
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}}
                <input type="submit" value="change">
            </form>

        </div>
        <div class="col-2"></div>
    </div>
</div>

</body>
</html>

crm/templates/employees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #5000ca">
        <div class="container">
          <a class="navbar-brand text-white" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{%url 'signup' %}">AddNewEmployee</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white" href="{%url 'employees' %}">ListAllEmployees</a>
              </li>


            </ul>
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="" class="nav-link text-white">contactUs</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'signout' %}" class="nav-link text-white">LogOut</a>
                </li>
            </ul>

          </div>
        </div>
      </nav>

<div class="container">


    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">

            <table class="table">

                <tr>
                    <td>Employeename</td>
                    <td>phone</td>
                    <td>email</td>
                    <td>Depertmeyt</td>
                    <td>Action</td>
                </tr>
                {%for emp in employees%}
                <tr>
                    <td>{{emp.first_name}}</td>
                    <td>{{emp.email}}</td>
                    <td>{{emp.phone}}</td>
                    <td>{{emp.department}}</td>

                    <td>
                        <a href="{%url 'empdetail' emp.id%}" class="btn btn-success">View</a>


                        <a href="{%url 'employeechange' emp.id%}" class="btn btn-danger">Edit</a>

                        <a href="" class="btn btn-primary">Delete</a>
                    </td>
                </tr>

                {%endfor%}
            </table>
        </div>
        <div class="col-1"></div>
    </div>
</div>

<foooter style="position:fixed;bottom:0;">

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#5000ca" fill-opacity="1" d="M0,256L34.3,245.3C68.6,235,137,213,206,186.7C274.3,160,343,128,411,138.7C480,149,549,203,617,213.3C685.7,224,754,192,823,186.7C891.4,181,960,203,1029,218.7C1097.1,235,1166,245,1234,245.3C1302.9,245,1371,235,1406,229.3L1440,224L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z"></path></svg>

</foooter>
</body>
</html>

crm/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #5000ca">
        <div class="container">
          <a class="navbar-brand text-white" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-white" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{%url 'signup' %}">AddNewEmployee</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white" href="{%url 'employees' %}">ListAllEmployees</a>
              </li>


            </ul>
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="" class="nav-link text-white">contactUs</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'signout' %}" class="nav-link text-white">LogOut</a>
                </li>
            </ul>

          </div>
        </div>
      </nav>
<h1>home</h1>
<a href="{%url 'signout' %}">logout</a>
<a href="{%url 'signup' %}">AddEmployee</a>
<a href="{%url 'employees' %}">ListAllEmployees</a>

<div class="container-fluid">


<foooter style="position:fixed;bottom:0; width:100%">

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#5000ca" fill-opacity="1" d="M0,256L34.3,245.3C68.6,235,137,213,206,186.7C274.3,160,343,128,411,138.7C480,149,549,203,617,213.3C685.7,224,754,192,823,186.7C891.4,181,960,203,1029,218.7C1097.1,235,1166,245,1234,245.3C1302.9,245,1371,235,1406,229.3L1440,224L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z"></path></svg>

</foooter>
</div>
</body>
</html>

crm/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<div class="container mt-5">
  <div class="row mt-5">
    <div class="col-1"></div>
    <div class="col-10">
      <form action="" method="post">
        {%csrf_token%}
        <div class="row mt-2">
          <div class="col-4">
            <input type="text" id="id_phone" name="phone" class="form-control" placeholder="phone">
          </div>

          <div class="col-4">
             <input type="text" id="id_first_name" name="first_name" class="form-control" placeholder="enter firstname">
          </div>
          <div class="col-4">
            <input type="text" id="id_last_name" name="last_name" class="form-control" placeholder="enter last name">

          </div>
        </div>

        <div class="row mt-4">
          <div class="col-4">
            <input type="text" id="id_address1" name="address1" class="form-control" placeholder="address1">
          </div>
          <div class="col-4">
             <input type="text" id="id_address2" name="address2" class="form-control" placeholder="address2">
          </div>
          <div class="col-4">
            <input type="text" id="id_designation" name="designation" class="form-control" placeholder="designation">

          </div>
        </div>

        <div class="row mt-4">

          <div class="col-4">
             <input type="text" id="id_city" name="city" class="form-control" placeholder="city">
          </div>
           <div class="col-4">
            <input type="text" id="id_pin" name="pin" class="form-control" placeholder="enter pin">
          </div>
          <div class="col-4">
            <label for="">Select State</label>
           {{form.state}}
          </div>
        </div>


        <div class="row mt-4">
          <div class="col-4">
             <input type="text" id="id_email" name="email" class="form-control" placeholder="email">
          </div>

          <div class="col-4">
            <input type="text" id="id_password1" name="password1" class="form-control" placeholder="password1">
          </div>
          <div class="col-4">
             <input type="text" id="id_password2" name="password2" class="form-control" placeholder="password2">
          </div>


        </div>

        <div class="row mt-5">
          <div class="col-4"></div>
          <div class="col-4">
            <input type="submit" value="Adduser" class="btn btn-success form-control">
          </div>
          <div class="col-4"></div>
        </div>
      </form>
    </div>
    <div class="col-1"></div>
  </div>
</div>
<foooter style="position:fixed;bottom:0;">

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#5000ca" fill-opacity="1" d="M0,256L34.3,245.3C68.6,235,137,213,206,186.7C274.3,160,343,128,411,138.7C480,149,549,203,617,213.3C685.7,224,754,192,823,186.7C891.4,181,960,203,1029,218.7C1097.1,235,1166,245,1234,245.3C1302.9,245,1371,235,1406,229.3L1440,224L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z"></path></svg>

</foooter>
</body>
</html>

crm/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
<div class="container border mt-5 mb-5">
  <div class="row mt-5 mb-3 ">
    <div class="col-2"></div>
    <div class="col-8">
      <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="create">
      </form>
      <h5>new User?<a href="{%url 'signup'%}">create new Account</a></h5>
    </div>
    <div class="col-2"></div>
  </div>
</div>
<foooter style="position:fixed;bottom:0;">

<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#5000ca" fill-opacity="1" d="M0,256L34.3,245.3C68.6,235,137,213,206,186.7C274.3,160,343,128,411,138.7C480,149,549,203,617,213.3C685.7,224,754,192,823,186.7C891.4,181,960,203,1029,218.7C1097.1,235,1166,245,1234,245.3C1302.9,245,1371,235,1406,229.3L1440,224L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z"></path></svg>

</foooter>
</body>
</html>